version: '3.1'

volumes:
  db-data:
    driver: local

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #  web:
  #    build: .
  #    ports:
  #      - "8000:5000"

  web:
    build: ./api
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html

  redis:
    image: "redis:alpine"